_updown.*: script cleanup

diff --git a/programs/_updown.mast/_updown.mast.in b/programs/_updown.mast/_updown.mast.in
--- a/programs/_updown.mast/_updown.mast.in
+++ b/programs/_updown.mast/_updown.mast.in
@@ -5,12 +5,12 @@
 # Copyright (C) 2002-2007 Michael Richardson <mcr@xelerance.com>
 # Copyright (C) 2003-2013 Tuomo Soini <tis@foobar.fi>
 # Copyright (C) 2008 Paul Wouters <paul@xelerance.com>
-# 
+#
 # This program is free software; you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by the
 # Free Software Foundation; either version 2 of the License, or (at your
 # option) any later version.  See <http://www.fsf.org/copyleft/gpl.txt>.
-# 
+#
 # This program is distributed in the hope that it will be useful, but
 # WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 # or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
@@ -22,7 +22,7 @@
 # that, and use the (left/right)updown= parameters in ipsec.conf to make
 # Libreswan use yours instead of this default one.
 
-test $IPSEC_INIT_SCRIPT_DEBUG && set -v -x
+test ${IPSEC_INIT_SCRIPT_DEBUG} && set -v -x
 
 LC_ALL=C
 export LC_ALL
@@ -30,7 +30,7 @@ export LC_ALL
 # things that this script gets (from ipsec_pluto(8) man page)
 #
 #
-#      PLUTO_VERSION
+#	PLUTO_VERSION
 #		indicates  what	 version of this interface is being
 #		used.  This document describes version	1.1.   This
 #		is upwardly compatible with version 1.0.
@@ -49,7 +49,8 @@ export LC_ALL
 #
 #	PLUTO_CONN_POLICY
 #		the policy of the connection, as in:
-#     RSASIG+ENCRYPT+TUNNEL+PFS+DONTREKEY+OPPORTUNISTIC+failureDROP+lKOD+rKOD  
+#		RSASIG+ENCRYPT+TUNNEL+PFS+DONTREKEY+OPPORTUNISTIC
+#		+failureDROP+lKOD+rKOD
 #
 #	PLUTO_NEXT_HOP
 #		is the next hop to which packets bound for the peer
@@ -167,22 +168,22 @@ ORIG_RESOLV_CONF=@FINALSYSCONFDIR@/resolv.conf
 use_comment=true
 
 # check interface version
-case "$PLUTO_VERSION" in
+case "${PLUTO_VERSION}" in
     1.*)
 	# Older Pluto?!?  Play it safe, script may be using new features.
-	echo "$0: obsolete interface version \"$PLUTO_VERSION\"," >&2
-	echo "$0: 	called by obsolete Pluto?" >&2
+	echo "${0}: obsolete interface version \"${PLUTO_VERSION}\"," >&2
+	echo "${0}: 	called by obsolete Pluto?" >&2
 	exit 2
 	;;
     2.*)
 	;;
-    *)	echo "$0: unknown interface version \"$PLUTO_VERSION\"" >&2
+    *)	echo "${0}: unknown interface version \"${PLUTO_VERSION}\"" >&2
 	exit 2
 	;;
 esac
 
 # check parameter(s)
-case "$1:$*" in
+case "${1}:$*" in
     ':')
 	# no parameters
 	;;
@@ -190,7 +191,7 @@ case "$1:$*" in
 	# custom parameters (see above CAUTION comment)
 	;;
     *)
-	echo "$0: unknown parameters \"$*\"" >&2
+	echo "${0}: unknown parameters \"$*\"" >&2
 	exit 2
 	;;
 esac
@@ -198,53 +199,53 @@ esac
 # function to see if iptables has an IPSEC chain already, and if not,
 # it will create one and insert it into the OUTPUT and FORWARD chains.
 checkipsec() {
-    if [ -z "$PLUTO_SAREF_TRACKING" -o "$PLUTO_SAREF_TRACKING" = "no" ]; then
+    if [ -z "${PLUTO_SAREF_TRACKING}" -o "${PLUTO_SAREF_TRACKING}" = "no" ]; then
 	echo "SAref table initialisation left to third party"
-    elif [ -z "$PLUTO_CONN_ADDRFAMILY" -o "$PLUTO_CONN_ADDRFAMILY" = "ipv6" ]; then
+    elif [ -z "${PLUTO_CONN_ADDRFAMILY}" -o "${PLUTO_CONN_ADDRFAMILY}" = "ipv6" ]; then
 	echo "SAref not activated for IPv6"
     else
 	# make sure we have an IPSEC chain
 	if ! ( iptables -n -t mangle -L IPSEC >/dev/null 2>&1); then
-            iptables -t mangle -N IPSEC
+	    iptables -t mangle -N IPSEC
 	fi
 
 	# we also need to have a NEW_IPSEC_CONN chain
 	if ! ( iptables -n -t mangle -L NEW_IPSEC_CONN >/dev/null 2>&1); then
-            iptables -t mangle -N NEW_IPSEC_CONN
+	    iptables -t mangle -N NEW_IPSEC_CONN
 	fi
 
 	# initialize the IPSEC chain if needed
-	if [ "$PLUTO_SAREF_TRACKING" = "conntrack" ]; then
-            if [ "$(iptables -n -t mangle -L IPSEC | wc -l )" != 6 ]; then
+	if [ "${PLUTO_SAREF_TRACKING}" = "conntrack" ]; then
+	    if [ "$(iptables -n -t mangle -L IPSEC | wc -l )" != 6 ]; then
 		iptables -t mangle -F IPSEC
 		iptables -t mangle -A IPSEC -j CONNMARK --restore-mark
 		iptables -t mangle -A IPSEC -m mark --mark 0x80000000/0x80000000 -j RETURN
 		iptables -t mangle -A IPSEC -j NEW_IPSEC_CONN
 		iptables -t mangle -A IPSEC -j CONNMARK --save-mark
-            fi
+	    fi
 	else
-            if [ "$(iptables -n -t mangle -L IPSEC | wc -l )" != 3 ]; then
+	    if [ "$(iptables -n -t mangle -L IPSEC | wc -l )" != 3 ]; then
 		iptables -t mangle -F IPSEC
 		iptables -t mangle -A IPSEC -j NEW_IPSEC_CONN
-            fi
+	    fi
 	fi
 
 	# next, setup routing rules and tables:
 	# we pick table 50, cause proto50=ESP
 	if ! ( ip rule show | grep -qF 'from all fwmark 0x80000000/0x80000000 lookup 50' ); then
-            # note "fwmarkmask" is an (obsolete) Libreswan patch to "ip" command.
-            # note2: iproute2-2.6.22-070710 supports mask via /mask notation instead
-            # ip rule add fwmark 0x80000000 fwmarkmask 0x80000000 table 50
-            ip rule add from all fwmark 0x80000000/0x80000000 lookup 50
-            # This rule makes sure that packets originating from mast0 (ones that came
-            # out of a tunnel) go directly to the main table.  This makes sure that
-            # rp_filter can find the right reverse path route.
-            ip rule add from all iif $PLUTO_INTERFACE lookup main
+	    # note "fwmarkmask" is an (obsolete) Libreswan patch to "ip" command.
+	    # note2: iproute2-2.6.22-070710 supports mask via /mask notation instead
+	    # ip rule add fwmark 0x80000000 fwmarkmask 0x80000000 table 50
+	    ip rule add from all fwmark 0x80000000/0x80000000 lookup 50
+	    # This rule makes sure that packets originating from mast0 (ones that came
+	    # out of a tunnel) go directly to the main table.  This makes sure that
+	    # rp_filter can find the right reverse path route.
+	    ip rule add from all iif ${PLUTO_INTERFACE} lookup main
 	fi
 
 	# the default route goes over the mast interface
-	if ! ( ip route show table 50 | grep -qF "default dev $PLUTO_INTERFACE" ); then
-            ip route add default dev $PLUTO_INTERFACE table 50
+	if ! ( ip route show table 50 | grep -qF "default dev ${PLUTO_INTERFACE}" ); then
+	    ip route add default dev ${PLUTO_INTERFACE} table 50
 	fi
 
 	# now look for -j IPSEC in OUTPUT chains.
@@ -261,17 +262,17 @@ checkipsec() {
 	    iptables -t mangle -I PREROUTING 1 -j IPSEC
 	fi
 
-	if [ -w /proc/sys/net/ipv4/conf/$PLUTO_INTERFACE/src_valid_mark ]; then
-            # finally make sure that the top bit of source vmark for mast0 is set
-            vmark=$(cat /proc/sys/net/ipv4/conf/$PLUTO_INTERFACE/src_valid_mark)
-            vmark=$(( $vmark | 0x80000000 ))
-            echo "$vmark" > /proc/sys/net/ipv4/conf/$PLUTO_INTERFACE/src_valid_mark
+	if [ -w /proc/sys/net/ipv4/conf/${PLUTO_INTERFACE}/src_valid_mark ]; then
+	    # finally make sure that the top bit of source vmark for mast0 is set
+	    vmark=$(cat /proc/sys/net/ipv4/conf/${PLUTO_INTERFACE}/src_valid_mark)
+	    vmark=$(( ${vmark} | 0x80000000 ))
+	    echo "${vmark}" > /proc/sys/net/ipv4/conf/${PLUTO_INTERFACE}/src_valid_mark
 	else
-            # In case that we don't have the means to get rp_filter to cooperate 
-            # with KLIPS nfmark based routing scheme, we disable rp_filter.
-            for n in /proc/sys/net/ipv4/conf/*/rp_filter; do
-		echo 0 > $n
-            done
+	    # In case that we don't have the means to get rp_filter to cooperate
+	    # with KLIPS nfmark based routing scheme, we disable rp_filter.
+	    for n in /proc/sys/net/ipv4/conf/*/rp_filter; do
+		echo 0 > ${n}
+	    done
 	fi
     fi
 }
@@ -305,47 +306,47 @@ downrule() {
 }
 
 updateresolvconf() {
-    if [ -n "$PLUTO_CISCO_DNS_INFO" ]; then
-        if [ -n "$(pidof unbound)" -a -n "$PLUTO_CISCO_DOMAIN_INFO"  ]; then
-            echo "updating local nameserver for $PLUTO_CISCO_DOMAIN_INFO with $PLUTO_CISCO_DNS_INFO"
-            /usr/sbin/unbound-control forward_add $PLUTO_CISCO_DOMAIN_INFO $PLUTO_CISCO_DNS_INFO
-            /usr/sbin/unbound-control flush_zone $PLUTO_CISCO_DOMAIN_INFO
-            return
+    if [ -n "${PLUTO_CISCO_DNS_INFO}" ]; then
+	if [ -n "$(pidof unbound)" -a -n "${PLUTO_CISCO_DOMAIN_INFO}"  ]; then
+	    echo "updating local nameserver for ${PLUTO_CISCO_DOMAIN_INFO} with ${PLUTO_CISCO_DNS_INFO}"
+	    /usr/sbin/unbound-control forward_add ${PLUTO_CISCO_DOMAIN_INFO} ${PLUTO_CISCO_DNS_INFO}
+	    /usr/sbin/unbound-control flush_zone ${PLUTO_CISCO_DOMAIN_INFO}
+	    return
 	fi
     fi
 
-    if [ -z "$PLUTO_NM_CONFIGURED" -o "$PLUTO_NM_CONFIGURED" = 0 ]; then
+    if [ -z "${PLUTO_NM_CONFIGURED}" -o "${PLUTO_NM_CONFIGURED}" = 0 ]; then
 	echo "updating resolvconf"
-	if [ -e "$LIBRESWAN_RESOLV_CONF" ]; then
-            echo "Backup resolv.conf already exists, so doing nothing"
-            return 1
+	if [ -e "${LIBRESWAN_RESOLV_CONF}" ]; then
+	    echo "Backup resolv.conf already exists, so doing nothing"
+	    return 1
 	fi
 
-	if [ ! -e "$ORIG_RESOLV_CONF" ]; then
-            echo "resolv.conf does not exist, so doing nothing"
-            return 1
+	if [ ! -e "${ORIG_RESOLV_CONF}" ]; then
+	    echo "resolv.conf does not exist, so doing nothing"
+	    return 1
 	fi
 
-	cp -- $ORIG_RESOLV_CONF $LIBRESWAN_RESOLV_CONF
+	cp -- ${ORIG_RESOLV_CONF} ${LIBRESWAN_RESOLV_CONF}
 
 	RESOLVE_CONF="#Generated by Libreswan (IPSec)"
 
-	if [ -n "$PLUTO_CISCO_DOMAIN_INFO" ]; then
-	    if grep 'domain' $ORIG_RESOLV_CONF > /dev/null 2>&1; then
-		RESOLVE_CONF="$RESOLVE_CONF\ndomain $PLUTO_CISCO_DOMAIN_INFO\nsearch $PLUTO_CISCO_DOMAIN_INFO"
+	if [ -n "${PLUTO_CISCO_DOMAIN_INFO}" ]; then
+	    if grep 'domain' ${ORIG_RESOLV_CONF} > /dev/null 2>&1; then
+		RESOLVE_CONF="${RESOLVE_CONF}\ndomain ${PLUTO_CISCO_DOMAIN_INFO}\nsearch ${PLUTO_CISCO_DOMAIN_INFO}"
 	    else
-		RESOLVE_CONF="$RESOLVE_CONF\nsearch $PLUTO_CISCO_DOMAIN_INFO"
+		RESOLVE_CONF="${RESOLVE_CONF}\nsearch ${PLUTO_CISCO_DOMAIN_INFO}"
 	    fi
 	fi
 
-	if [ -n "$PLUTO_CISCO_DNS_INFO" ]; then
-	    for i in $PLUTO_CISCO_DNS_INFO; do
-		RESOLVE_CONF="$RESOLVE_CONF\nnameserver $i"
+	if [ -n "${PLUTO_CISCO_DNS_INFO}" ]; then
+	    for i in ${PLUTO_CISCO_DNS_INFO}; do
+		RESOLVE_CONF="${RESOLVE_CONF}\nnameserver ${i}"
 	    done
 	fi
 
-	rm -f -- $ORIG_RESOLV_CONF
-	printf "$RESOLVE_CONF" > $ORIG_RESOLV_CONF
+	rm -f -- ${ORIG_RESOLV_CONF}
+	printf "${RESOLVE_CONF}" > ${ORIG_RESOLV_CONF}
 	return $?
     else
 	echo "Updating resolv.conf is controlled by Network Manager"
@@ -355,29 +356,29 @@ updateresolvconf() {
 
 restoreresolvconf() {
     if [ -n "$(pidof unbound)" ]; then
-	if [ -n "$PLUTO_CISCO_DNS_INFO" ]; then
-            echo "flushing local nameserver of $PLUTO_CISCO_DOMAIN_INFO"
-            /usr/sbin/unbound-control forward_remove $PLUTO_CISCO_DOMAIN_INFO
-            /usr/sbin/unbound-control flush_zone $PLUTO_CISCO_DOMAIN_INFO
+	if [ -n "${PLUTO_CISCO_DNS_INFO}" ]; then
+	    echo "flushing local nameserver of ${PLUTO_CISCO_DOMAIN_INFO}"
+	    /usr/sbin/unbound-control forward_remove ${PLUTO_CISCO_DOMAIN_INFO}
+	    /usr/sbin/unbound-control flush_zone ${PLUTO_CISCO_DOMAIN_INFO}
 	fi
 	return
     fi
 
-    if [ -z "$PLUTO_NM_CONFIGURED" -o "$PLUTO_NM_CONFIGURED" = 0 ]; then
+    if [ -z "${PLUTO_NM_CONFIGURED}" -o "${PLUTO_NM_CONFIGURED}" = 0 ]; then
 	echo "restoring resolvconf"
 
-	if [ ! -e "$LIBRESWAN_RESOLV_CONF" ]; then
+	if [ ! -e "${LIBRESWAN_RESOLV_CONF}" ]; then
 	    echo "Problem in restoring the resolv.conf, as there is no backup file"
 	    return 2
 	fi
 
-	if grep 'Libreswan' $ORIG_RESOLV_CONF > /dev/null 2>&1; then
-	    cp -- "$LIBRESWAN_RESOLV_CONF" $ORIG_RESOLV_CONF
+	if grep 'Libreswan' ${ORIG_RESOLV_CONF} > /dev/null 2>&1; then
+	    cp -- "${LIBRESWAN_RESOLV_CONF}" ${ORIG_RESOLV_CONF}
 	else
 	    echo "Current resolv.conf is not generated by Libreswan, so doing nothing"
 	fi
 
-	rm -f -- "$LIBRESWAN_RESOLV_CONF"
+	rm -f -- "${LIBRESWAN_RESOLV_CONF}"
 	return 0
     else
 	# Here disconnect signal is sent to NetworkManager
@@ -394,7 +395,7 @@ restoreresolvconf() {
 }
 
 disconnectNM() {
-    # This will be called whenever a connection fails to establish 
+    # This will be called whenever a connection fails to establish
     # due to a state (either phase 1, xauth phase, or phase 2) fails.
     # This will send a singal to NetworkManager over dbus so that NM
     # can clear up coonnections.
@@ -410,12 +411,12 @@ addsource() {
     # check if given sourceip is local and add as alias if not
     if ! ip -o route get ${PLUTO_MY_SOURCEIP%/*} | grep -q ^local; then
 	it="ip addr add ${PLUTO_MY_SOURCEIP%/*}/32 dev ${PLUTO_INTERFACE%:*}"
-	oops="$(eval $it 2>&1)"
+	oops="$(eval ${it} 2>&1)"
 	st=$?
-	if [ -z "$oops" -a $st -ne 0 ]; then
-	    oops="silent error, exit status $st"
+	if [ -z "${oops}" -a ${st} -ne 0 ]; then
+	    oops="silent error, exit status ${st}"
 	fi
-	case "$oops" in
+	case "${oops}" in
 	    'RTNETLINK answers: File exists'*)
 		# should not happen, but ... ignore if the
 		# address was already assigned on interface
@@ -423,95 +424,95 @@ addsource() {
 		st=0
 		;;
 	esac
-	if [ -n "$oops" -o $st -ne 0 ]; then
-	    echo "$0: addsource \"$it\" failed ($oops)" >&2
+	if [ -n "${oops}" -o ${st} -ne 0 ]; then
+	    echo "${0}: addsource \"${it}\" failed (${oops})" >&2
 	fi
     fi
-    return $st
+    return ${st}
 }
 
 # WARNING: changesource might not work as expected with mast
 changesource() {
     st=0
-    parms="$PLUTO_PEER_CLIENT"
-    parms2="dev $PLUTO_INTERFACE"
-    parms3="src ${PLUTO_MY_SOURCEIP%/*}" 
-    if [ -n "$IPROUTETABLE" ]; then
-	parms3="$parms3 table $IPROUTETABLE"
+    parms="${PLUTO_PEER_CLIENT}"
+    parms2="dev ${PLUTO_INTERFACE}"
+    parms3="src ${PLUTO_MY_SOURCEIP%/*}"
+    if [ -n "${IPROUTETABLE}" ]; then
+	parms3="${parms3} table ${IPROUTETABLE}"
     fi
     cmd=add
     if ! ip -o route get ${PLUTO_MY_SOURCEIP%/*} | grep mast0; then
 	cmd=change
     fi
-    it="ip route $cmd $parms $parms2 $parms3"
-    case "$PLUTO_PEER_CLIENT" in
+    it="ip route ${cmd} ${parms} ${parms2} ${parms3}"
+    case "${PLUTO_PEER_CLIENT}" in
  	"0.0.0.0/0"|"::/0")
 	    # opportunistic encryption work around
 	    it=
  	    ;;
     esac
-    oops="$(eval $it 2>&1)"
+    oops="$(eval ${it} 2>&1)"
     st=$?
-    if [ -z  "$oops" -a $st -ne 0 ]; then
-	oops="silent error, exit status $st"
+    if [ -z  "${oops}" -a ${st} -ne 0 ]; then
+	oops="silent error, exit status ${st}"
     fi
-    if [ -n "$oops" -o $st -ne 0 ]; then
-	echo "$0: changesource \"$it\" failed ($oops)" >&2
+    if [ -n "${oops}" -o ${st} -ne 0 ]; then
+	echo "${0}: changesource \"${it}\" failed (${oops})" >&2
     fi
-    return $st
+    return ${st}
 }
 
 # the purpose of this command is to add an entry to the NEW_IPSEC_CONN chain
 # in the iptables system. It grabs the right packets and does a --set-mark
 # on them. An advanced routing rule then directs the packets to the
-# appropriate device with the right mark. 
+# appropriate device with the right mark.
 #
 # This is not be done for OE packets --- they are supposed to get a
 # new netfilter module instead.
 doipsecrule() {
-    if [ -z "$PLUTO_SAREF_TRACKING" -o "$PLUTO_SAREF_TRACKING" = "no" ]; then
+    if [ -z "${PLUTO_SAREF_TRACKING}" -o "${PLUTO_SAREF_TRACKING}" = "no" ]; then
 	echo "SAref tracking left to third party"
-    elif [ -z "$PLUTO_CONN_ADDRFAMILY" -o "$PLUTO_CONN_ADDRFAMILY" = "ipv6" ]; then
+    elif [ -z "${PLUTO_CONN_ADDRFAMILY}" -o "${PLUTO_CONN_ADDRFAMILY}" = "ipv6" ]; then
 	echo "SAref not activated for IPv6"
     else
-	saref=$PLUTO_PEER_REF
-	nf_saref=$(printf "0x%x0000" $(( $saref | 0x8000 )))
+	saref=${PLUTO_PEER_REF}
+	nf_saref=$(printf "0x%x0000" $(( ${saref} | 0x8000 )))
 
-	srcnet=$PLUTO_MY_CLIENT_NET/$PLUTO_MY_CLIENT_MASK
-	dstnet=$PLUTO_PEER_CLIENT_NET/$PLUTO_PEER_CLIENT_MASK
+	srcnet=${PLUTO_MY_CLIENT_NET}/${PLUTO_MY_CLIENT_MASK}
+	dstnet=${PLUTO_PEER_CLIENT_NET}/${PLUTO_PEER_CLIENT_MASK}
 
-	#echo SAref: $saref '->' $nf_saref
+	#echo SAref: ${saref} '->' ${nf_saref}
 
-        rulespec="--src $srcnet --dst $dstnet -m mark --mark 0/0x80000000 -j MARK --set-mark $nf_saref"
-        if $use_comment; then
-            # WARNING: you should only edit use_comment while you have no established conns
-            rulespec="$rulespec -m comment --comment '$PLUTO_CONNECTION'"
-        fi
+	rulespec="--src ${srcnet} --dst ${dstnet} -m mark --mark 0/0x80000000 -j MARK --set-mark ${nf_saref}"
+	if ${use_comment}; then
+	    # WARNING: you should only edit use_comment while you have no established conns
+	    rulespec="${rulespec} -m comment --comment '${PLUTO_CONNECTION}'"
+	fi
 
-	case $1 in
+	case ${1} in
 	    add)
-                it="iptables -t mangle -I NEW_IPSEC_CONN 1 $rulespec"
-                ;;
-            delete)
-                it="iptables -t mangle -D NEW_IPSEC_CONN $rulespec"
-                ;;
-        esac
+		it="iptables -t mangle -I NEW_IPSEC_CONN 1 ${rulespec}"
+		;;
+	    delete)
+		it="iptables -t mangle -D NEW_IPSEC_CONN ${rulespec}"
+		;;
+	esac
 
-	oops="$(set +x; eval $it 2>&1)"
+	oops="$(set +x; eval ${it} 2>&1)"
 	st=$?
-	if [ -z  "$oops" -a $st -ne 0 ]; then
-	    oops="silent error, exit status $st"
+	if [ -z  "${oops}" -a ${st} -ne 0 ]; then
+	    oops="silent error, exit status ${st}"
 	fi
-	if [ -n "$oops" -o $st -ne 0 ]; then
-	    echo "$0: doroute \"$it\" failed ($oops)" >&2
+	if [ -n "${oops}" -o ${st} -ne 0 ]; then
+	    echo "${0}: doipsecrule \"${it}\" failed (${oops})" >&2
 	fi
-	return $st
+	return ${st}
     fi
 }
- 
+
 
 # the big choice
-case "$PLUTO_VERB:$1" in
+case "${PLUTO_VERB}:${1}" in
     spdadd-client:*|spdadd-host:*)
 	checkipsec;
 	doipsecrule add;;
@@ -549,17 +550,17 @@ case "$PLUTO_VERB:$1" in
 	# If you are doing a custom version, firewall commands go here.
 	;;
     updateresolvconf-host|updateresolvconf-client)
-        # updating resolv.conf using DNS info obtained from the server
-        updateresolvconf
-        ;;
+	# updating resolv.conf using DNS info obtained from the server
+	updateresolvconf
+	;;
     restoreresolvconf-host|restoreresolvconf-client)
-        # restoring resolv.conf
-        restoreresolvconf
-        ;;
+	# restoring resolv.conf
+	restoreresolvconf
+	;;
     disconnectNM-host|disconnectNM-client)
-        # sending disconnect signal to NM, as something went wrong.
-        disconnectNM
-        ;;
+	# sending disconnect signal to NM, as something went wrong.
+	disconnectNM
+	;;
     #
     # IPv6
     #
@@ -590,7 +591,7 @@ case "$PLUTO_VERB:$1" in
 	# If you are doing a custom version, firewall commands go here.
 	;;
     *)
-	echo "$0: unknown verb \"$PLUTO_VERB\" or parameter \"$1\"" >&2
+	echo "${0}: unknown verb \"${PLUTO_VERB}\" or parameter \"${1}\"" >&2
 	exit 1
 	;;
 esac
