swan-build, swan-install and swan-update: - carefully log in /source/compile-log.txt - support /tmp or /source for build product (default /source) - for /tmp, make the product persistent by tar-ing to /source - (slightly risky) use "set -e" so script errors halt the script - (slightly crude) use "set -x" to indicate progress

diff --git a/testing/guestbin/swan-install b/testing/guestbin/swan-install
--- a/testing/guestbin/swan-install
+++ b/testing/guestbin/swan-install
@@ -1,18 +1,54 @@
 #!/bin/sh
+set -x
+
+set -ue
+
+# We use /tmp/... or /source/... for build output.
+# /tmp is a tmpfs and is faster but disappears on reboot.
+# /source is a shared plan9 filesystem: persistant but slow
+# When /tmp is used, we make the contents persist with tar.
+
+# Note: for some reason modobj always lives in /source
+
+OBJDIR="${OBJDIR:-/tmp/lsw_build}"
 
 pidof pluto >/dev/null && ipsec setup stop 2> /dev/null
 
 cd /source
 
+case "$OBJDIR" in
+/source/*)
+	;;
+/tmp/*)
+	# grab ephemeral build results
+	rm -rf "$OBJDIR"
+	tar xzf lsw_build.tgz --absolute-names
+	;;
+*)
+	echo "$0: OBJDIR does not start with /source/ or /tmp/" >&2
+	exit 1
+	;;
+esac
+
 # we use /tmp because it is on tmpfs and compiles much faster, even faster
 # than using ccache on the regular disk image files.
-make OBJDIR=/tmp/lsw_build install 2>&1 >> compile-log.txt
 
-make module_install 2>&1 >> compile-log.txt
+echo ">>> $0 on `hostname` at `date`" >>compile-log.txt
+
+if ! make OBJDIR="$OBJDIR" install >>compile-log.txt 2>&1
+then
+	echo '"make install"'" failed: $?; see compile-log.txt"
+fi
+
+if ! make module_install >>compile-log.txt 2>&1
+then
+	echo '"make module_install"'" failed: $?; see compile-log.txt"
+fi
 
 # ensure selinux bits
 restorecon /usr/local/sbin -Rv
 restorecon /usr/local/libexec/ipsec -Rv
+
 # disable autostarting via service or systemd
 if [ -x /usr/bin/systemctl -o -x /usr/sbin/systemctl -o -x /sbin/systemctl ] ; then
 	sed -i "s/Restart=always/Restart=no/" /lib/systemd/system/ipsec.service
@@ -21,3 +57,5 @@ if [ -x /usr/bin/systemctl -o -x /usr/sbin/systemctl -o -x /sbin/systemctl ] ; t
 else
 	service ipsec disable
 fi
+
+echo "$0 finished on `hostname` at `date`"
