testing: swan-build and swan-install abort on finding pluto in /usr/libexec
This ensures no /usr/local build is installed when a libreswan (or
openswan) package is installed on the server already.

diff --git a/testing/guestbin/swan-build b/testing/guestbin/swan-build
--- a/testing/guestbin/swan-build
+++ b/testing/guestbin/swan-build
@@ -6,6 +6,12 @@ set -ue
 
 cd /source
 
+if [ -f /usr/libexec/ipsec/pluto ]
+then
+	echo "ABORT: found pluto outside /usr/local"
+	exit 1;
+fi
+
 # we don't trust all makefile dependancies, esp lib/
 rm -rf OBJ.linux.* modobj
 
diff --git a/testing/guestbin/swan-install b/testing/guestbin/swan-install
--- a/testing/guestbin/swan-install
+++ b/testing/guestbin/swan-install
@@ -3,6 +3,12 @@ set -x
 
 set -ue
 
+if [ -f /usr/libexec/ipsec/pluto ]
+then
+	echo "ABORT: existing pluot found outside /usr/local/"
+	exit 1
+fi
+
 pidof pluto >/dev/null && ipsec setup stop 2> /dev/null
 
 cd /source
