scripts: big script cleanup unifying coding style to new one where possible. This cleanup also fixes multiple bugs in scripts. Also this should fix libreswan bug #50.

diff --git a/initsystems/sysvinit/init.rhel.in b/initsystems/sysvinit/init.rhel.in
--- a/initsystems/sysvinit/init.rhel.in
+++ b/initsystems/sysvinit/init.rhel.in
@@ -2,13 +2,13 @@
 # IPsec startup and shutdown script
 #
 ### BEGIN INIT INFO
-# Provides:          ipsec
-# Required-Start:    $network $remote_fs $syslog $named
-# Required-Stop:     $syslog $remote_fs
+# Provides: ipsec
+# Required-Start: $network $remote_fs $syslog $named
+# Required-Stop: $syslog $remote_fs
 # Default-Start:
-# Default-Stop:      0 1 6
+# Default-Stop: 0 1 6
 # Short-Description: Start Libreswan IPsec at boot time
-# Description:       Enable automatic key management for IPsec (KLIPS and NETKEY)
+# Description: Enable automatic key management for IPsec (KLIPS and NETKEY)
 ### END INIT INFO
 #
 ### see https://bugzilla.redhat.com/show_bug.cgi?id=636572
@@ -18,24 +18,24 @@
 # Copyright (C) 2002              Michael Richardson <mcr@freeswan.org>
 # Copyright (C) 2006              Michael Richardson <mcr@xelerance.com>
 # Copyright (C) 2008              Michael Richardson <mcr@sandelman.ca>
-# Copyright (C) 2008-2011         Tuomo Soini <tis@foobar.fi>
+# Copyright (C) 2008-2011, 2013   Tuomo Soini <tis@foobar.fi>
 # Copyright (C) 2012              Paul Wouters <paul@libreswan.org>
-# 
+#
 # This program is free software; you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by the
 # Free Software Foundation; either version 2 of the License, or (at your
 # option) any later version.  See <http://www.fsf.org/copyleft/gpl.txt>.
-# 
+#
 # This program is distributed in the hope that it will be useful, but
 # WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 # or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 # for more details.
 #
-# ipsec         sysv style init.d script for starting and stopping
-#               the IPsec security subsystem (KLIPS and Pluto).
+# ipsec		sysv style init.d script for starting and stopping
+#		the IPsec security subsystem (KLIPS and Pluto).
 #
-# This script becomes /etc/rc.d/init.d/ipsec (or possibly /etc/init.d/ipsec)
-# and is also accessible as "ipsec setup" 
+# This script becomes /etc/rc.d/init.d/ipsec
+# and is also accessible as "ipsec setup"
 #
 # The startup and shutdown times are a difficult compromise (in particular,
 # it is almost impossible to reconcile them with the insanely early/late
@@ -49,7 +49,7 @@
 test $IPSEC_INIT_SCRIPT_DEBUG && set -v -x
 
 # Source function library.
-. /etc/init.d/functions
+. /etc/rc.d/init.d/functions
 
 # Check that networking is up.
 [ "${NETWORKING}" = "no" ] && exit 6
@@ -58,202 +58,180 @@ if [ ! -f /etc/sysconfig/network ]; then
     exit 6
 fi
 
-if [ `id -u` -ne 0 ]
-then
+if [ $(id -u) -ne 0 ]; then
     echo "permission denied (must be superuser)" |
-      logger -s -p daemon.error -t ipsec_setup 2>&1
+	logger -s -p daemon.error -t ipsec_setup 2>&1
     exit 4
 fi
 
-if test `ip addr list|grep -c cipsec` -ne 0
-then
-	echo "Cisco IPSec client is already loaded, aborting! (cipsec# device found)"
-	exit 1
+if [ $(ip addr list | grep -c cipsec) -ne 0 ]; then
+    echo "Cisco IPSec client is already loaded, aborting! (cipsec# device found)"
+    exit 1
 fi
 
 # where the private directory and the config files are
-IPSEC_CONF="${FINALCONFFILE-@FINALCONFFILE@}"
-IPSEC_EXECDIR="${IPSEC_EXECDIR-@IPSEC_EXECDIR@}"
-IPSEC_LIBDIR="${IPSEC_LIBDIR-@IPSEC_LIBDIR@}"
-IPSEC_SBINDIR="${IPSEC_SBINDIR-@IPSEC_SBINDIR@}"
+IPSEC_CONF="${IPSEC_CONF:-/etc/ipsec.conf}"
+IPSEC_EXECDIR="${IPSEC_EXECDIR:-/usr/libexec/ipsec}"
+IPSEC_LIBDIR="${IPSEC_LIBDIR:-/usr/libexec/ipsec}"
+IPSEC_SBINDIR="${IPSEC_SBINDIR:-/usr/sbin}"
+unset PLUTO_OPTIONS
 
 rundir=/var/run/pluto
-plutopid=$rundir/pluto.pid
-plutoctl=$rundir/pluto.ctl
+plutopid=${rundir}/pluto.pid
+plutoctl=${rundir}/pluto.ctl
+lockdir=/var/lock/subsys
+lockfile=${lockdir}/ipsec
 ipsecversion=/proc/net/ipsec_version
 kamepfkey=/proc/net/pfkey
 
-#/etc/resolv.conf related paths
-LIBRESWAN_RESOLV_CONF=/var/run/pluto/libreswan-resolv-conf-backup
+# /etc/resolv.conf related paths
+LIBRESWAN_RESOLV_CONF=${rundir}/libreswan-resolv-conf-backup
 ORIG_RESOLV_CONF=/etc/resolv.conf
 
 # there is some confusion over the name - just do both
-if [ -f /etc/sysconfig/ipsec ]; then
-     . /etc/sysconfig/ipsec
-fi
-if [ -f /etc/sysconfig/pluto ]; then
-     . /etc/sysconfig/pluto
-fi
+[ -f /etc/sysconfig/ipsec ] && . /etc/sysconfig/ipsec
+[ -f /etc/sysconfig/pluto ] && . /etc/sysconfig/pluto
 
 # misc setup
 umask 022
 
-if [ -z "$IPSEC_SBINDIR" ]
-then
-        $IPSEC_SBINDIR="${IPSEC_SBINDIR-@IPSEC_SBINDIR@}"
-fi
 # standardize PATH, and export it for everything else's benefit
-PATH="${IPSEC_SBINDIR}":/sbin:/usr/sbin:/usr/local/bin:/bin:/usr/bin
+PATH="${IPSEC_SBINDIR}:/sbin:/usr/sbin:/usr/local/bin:/bin:/usr/bin"
 export PATH
 
-mkdir -p /var/run/pluto
-chmod 700 /var/run/pluto
+mkdir -p ${rundir}
+chmod 700 ${rundir}
 
 verify_config() {
-    test -f $IPSEC_CONF || exit 6
+    [ -f ${IPSEC_CONF} ] || exit 6
 
-    config_error=`ipsec addconn --config $IPSEC_CONF --checkconfig 2>&1`
+    config_error=$(ipsec addconn --config ${IPSEC_CONF} --checkconfig 2>&1)
     RETVAL=$?
-    if [ $RETVAL != 0 ]
-    then
+    if [ ${RETVAL} -gt 0 ]; then
         echo "Configuration error - the following error occured:"
-        echo $config_error
+        echo ${config_error}
         echo "IKE daemon status was not modified"
-        exit $RETVAL
+        exit ${RETVAL}
     fi
 }
 
 start() {
-	echo -n "Starting pluto IKE daemon for IPsec: "
-	ipsec _stackmanager start
+    echo -n $"Starting pluto IKE daemon for IPsec: "
+    ipsec _stackmanager start
 
-	#pluto searches the current directory, so this is required for making it selinux compliant
-	cd /
-	# This script will enter an endless loop to ensure pluto restarts on crash
-	ipsec _plutorun &
-	RETVAL=$?
-	if [ $RETVAL -eq 0 ];
-	then
-		success; echo
-	else
-		failure; echo; return $RETVAL
-	fi
-	if [ ! -d /var/lock/subsys ]
-	then
-		mkdir -p /var/lock/subsys
-	fi
-	touch /var/lock/subsys/ipsec
-	return $RETVAL
+    # pluto searches the current directory, so this is required for making it selinux compliant
+    cd /
+    # This script will enter an endless loop to ensure pluto restarts on crash
+    ipsec _plutorun --extraoptions "$PLUTO_OPTIONS" &
+    RETVAL=$?
+    if [ ${RETVAL} -eq 0 ]; then
+	success
+	[ -d ${lockdir} ] || mkdir -p ${lockdir}
+	touch ${lockfile}
+    else
+	failure
+    fi
+    echo
+    return ${RETVAL}
 }
 
 
 stop() {
-	if [ ! -e $plutoctl ]
-	then
-		echo "Missing control file $plutoctl - is pluto running?"
-	else
-		echo "Shutting down pluto IKE daemon"
-		ipsec whack --shutdown
-		for waitsec in 1 2 3 4 5 6 7 8 9 10 # don't use seq, might not exist on embedded
-		do
-			if [ -s $plutopid ]
-			then
-				echo -n "."
-				sleep 1
-			else
-				break
-			fi
-		done
-		echo ""
-		rm -f $plutoctl # we won't be using this anymore
-
-		if [ -s $plutopid ] # pluto did not die peacefully
-		then
-			echo "Attempt to shut Pluto down failed!  Trying kill"
-			if [ -d /proc/$plutopid ]
-			then
-				kill `cat $plutopid` 
-				RETVAL=$?
-				sleep 5;
-				if [ $RETVAL -ne 0 ]
-				then
-				echo "Kill failed - removing orphaned $plutopid"
-				fi
-			else
-				echo "Removing orphaned $plutopid"
-			fi
-			rm -f $plutopid
-		fi
+    if [ ! -e ${plutoctl} ]; then
+	echo "Missing control file ${plutoctl} - is pluto running?"
+    else
+	echo $"Shutting down pluto IKE daemon"
+	ipsec whack --shutdown
+	# don't use seq, might not exist on embedded
+	for waitsec in 1 2 3 4 5 6 7 8 9 10; do
+	    if [ -s ${plutopid} ]; then
+		echo -n "."
+		sleep 1
+	    else
+		break
+	    fi
+	done
+	echo
+	rm -f ${plutoctl} # we won't be using this anymore
+	if [ -s ${plutopid} ]; then
+	    # pluto did not die peacefully
+	    echo "Attempt to shut Pluto down failed!  Trying kill"
+	    killproc -p ${plutopid} ${IPSEC_EXECDIR}/pluto
+	    RETVAL=$?
+	    [ ${RETVAL} -eq 0 ] && rm -f ${plutopid}
 	fi
+    fi
 
-	ipsec _stackmanager stop
+    ipsec _stackmanager stop
 
-	#cleaning up backup resolv.conf
-	if [ -e $LIBRESWAN_RESOLV_CONF ]
-	then
-		if grep 'Libreswan' $ORIG_RESOLV_CONF > /dev/null 2>&1
-		then
-			cp $LIBRESWAN_RESOLV_CONF $ORIG_RESOLV_CONF
-		else
-			echo "Current resolv.conf is not generated by Libreswan, so doing nothing"
-		fi
-		rm -f  $LIBRESWAN_RESOLV_CONF
+    # cleaning up backup resolv.conf
+    if [ -e ${LIBRESWAN_RESOLV_CONF} ]; then
+	if grep 'Libreswan' ${ORIG_RESOLV_CONF} > /dev/null 2>&1; then
+	    cp ${LIBRESWAN_RESOLV_CONF} ${ORIG_RESOLV_CONF}
 	fi
+	rm -f  ${LIBRESWAN_RESOLV_CONF}
+    fi
 
-	rm -f /var/lock/subsys/ipsec
+    rm -f ${lockfile}
+    return ${RETVAL}
 }
 
 restart() {
     verify_config
     stop
     start
+    return $?
 }
 
 condrestart() {
     verify_config
-    /etc/init.d/ipsec status || exit 0
-    restart
-}
-
-status() {
-    
-    RETVAL=$?	
-    return $RETVAL
+    RETVAL=$?
+    if [ -f ${lockfile} ]; then
+	restart
+	RETVAL=$?
+    fi
+    return ${RETVAL}
 }
 
 version() {
     ipsec version
-    RETVAL=$?
-    return $RETVAL
+    return $?
 }
 
 
 # do it
 case "$1" in
     start)
-         start
-         ;;
+	start
+	RETVAL=$?
+	;;
     stop)
-         stop
-         ;;
+	stop
+	RETVAL=$?
+	;;
     restart)
-         restart
- 	 ;;
+	restart
+	RETVAL=$?
+	;;
     reload|force-reload)
-         restart
- 	 ;;
+	restart
+	RETVAL=$?
+	;;
     condrestart|try-restart)
-         condrestart
-         ;;
+	condrestart
+	RETVAL=$?
+	;;
     status)
-         status
-         ;;
+	status -p ${plutopid} -l ${lockfile} ${IPSEC_EXECDIR}/pluto
+	RETVAL=$?
+	;;
     version)
-         version
-         ;;
+	version
+	RETVAL=$?
+	;;
     *)
-         echo "Usage: $0 {start|stop|restart|reload|force-reload|condrestart|try-restart|status|version}"
-         RETVAL=2
+	echo "Usage: $0 {start|stop|restart|reload|force-reload|condrestart|try-restart|status|version}"
+	RETVAL=2
 esac
  	
-exit $RETVAL
+exit ${RETVAL}
diff --git a/programs/_plutorun/_plutorun.in b/programs/_plutorun/_plutorun.in
--- a/programs/_plutorun/_plutorun.in
+++ b/programs/_plutorun/_plutorun.in
@@ -1,7 +1,7 @@
 #!/bin/sh
 # Pluto control daemon
 # Copyright (C) 1998, 1999, 2001  Henry Spencer.
-# Copyright (C) 2010-2012 Tuomo Soini <tis@foobar.fi>
+# Copyright (C) 2010-2013 Tuomo Soini <tis@foobar.fi>
 # Copyright (C) 2012 Paul Wouters <paul@libreswan.org>
 # 
 # This program is free software; you can redistribute it and/or modify it
@@ -14,34 +14,49 @@
 # or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 # for more details.
 
-pidfile=/var/run/pluto/pluto.pid
+pidfile=@FINALVARDIR@/run/pluto/pluto.pid
 verb="Starting"
-for dummy
-do
-	case "$1" in
-	--re)	                 verb="Restarting"	;;
-	--plutorestartoncrash)   plutorestartoncrash="$2"; shift ;;
-	--)	                 shift ; break	;;
-	-*)	                 echo "ipsec _plutorun: unknown option \`$1'" >&2 ; exit 2	;;
-	*)	                 break	;;
-	esac
-	shift
+for dummy; do
+    case "$1" in
+	--re)
+	    verb="Restarting"
+	    ;;
+	--plutorestartoncrash)
+	    plutorestartoncrash="$2"
+	    shift
+	    ;;
+	--extraoptions)
+	    PLUTO_OPTIONS="$2"
+	    shift
+	    ;;
+	--)
+	    shift
+	    break
+	    ;;
+	-*)
+	    echo "ipsec _plutorun: unknown option \`$1'" >&2
+	    exit 2
+	    ;;
+	*)
+	    break
+	    ;;
+    esac
+    shift
 done
 
 # initially we are in the foreground, with parent looking after logging
 
 # precautions
-if test -f $pidfile
-then
-	echo "pluto appears to be running already (\`$pidfile' exists), will not start another"
-	exit 1
+if [ -f ${pidfile} ]; then
+    echo "pluto appears to be running already (\`$pidfile' exists), will not start another"
+    exit 1
 fi
 
-logger "Plutorun started on "`date` 
+logger "Plutorun started on "$(date)
 
 # spin off into the background, with our own logging
 echo "$verb Pluto subsystem..." | logger -p authpriv.error -t ipsec__plutorun
-execdir=${IPSEC_EXECDIR-@IPSEC_EXECDIR@}
+execdir=${IPSEC_EXECDIR:-@IPSEC_EXECDIR@}
 
 # Work around problem with broken shells (e.g. Busybox sh).
 # We are called with stdout & stderr going to a logger process started
@@ -57,45 +72,49 @@ exec 1>/dev/null
 exec 2>/dev/null
 
 until (
-	# eval allows to contain redirection and other magic
-	eval $execdir/pluto --config /etc/ipsec.conf --nofork 
-	status=$?
-	echo "exit"
-	echo $status
-	) 
+    # eval allows to contain redirection and other magic
+    eval $execdir/pluto --config @FINALIPSECCONF@ --nofork ${PLUTO_OPTIONS}
+    status=$?
+    echo "exit"
+    echo $status
+    ) 
 do
-	status=$?
-	case "$status" in
-	13)	echo "internal failure in pluto scripts, impossible to carry on"
-		exit 1
-		;;
-	10)	echo "pluto apparently already running (?!?), giving up"
-		exit 1
-		;;
-	137)	echo "pluto killed by SIGKILL, terminating without restart or unlock"
-		exit 0
-		;;
-	143)	echo "pluto killed by SIGTERM, terminating without restart"
-		# pluto now does its own unlock for this
-		exit 0
-		;;
-	*)	st=$status
+    status=$?
+    case "$status" in
+    13)
+	echo "internal failure in pluto scripts, impossible to carry on"
+	exit 1
+	;;
+    10)
+	echo "pluto apparently already running (?!?), giving up"
+	exit 1
+	;;
+    137)
+	echo "pluto killed by SIGKILL, terminating without restart or unlock"
+	exit 0
+	;;
+    143)
+	echo "pluto killed by SIGTERM, terminating without restart"
+	# pluto now does its own unlock for this
+	exit 0
+	;;
+    *)
+	st=$status
 
-		if test $st -gt 128
-		then
-			st="$st (signal `expr $st - 128`)"
-		fi
-		echo "!pluto failure!:  exited with error status $st"
-		echo "restarting IPsec after pause..."
-		(
-			sleep 10
-			# use start, not restart for now, due to module unloading/loading
-			ipsec setup start
-		) </dev/null >/dev/null 2>&1 &
-		exit 1
-		;;
-	esac
+	if [ $st -gt 128 ]; then
+	    st="$st (signal $(expr $st - 128))"
+	fi
+	echo "!pluto failure!:  exited with error status $st"
+	echo "restarting IPsec after pause..."
+	(
+	    sleep 10
+	    # use start, not restart for now, due to module unloading/loading
+	    ipsec setup start
+	) </dev/null >/dev/null 2>&1 &
+	exit 1
+	;;
+    esac
 done </dev/null 2>&1 |
-	logger -s -p daemon.error -t ipsec__plutorun >/dev/null 2>/dev/null &
+    logger -s -p daemon.error -t ipsec__plutorun >/dev/null 2>/dev/null &
 
 exit 0
