* fixup rhel init script. spin off start of debian specific  version

diff --git a/initsystems/sysvinit/init.debian.in b/initsystems/sysvinit/init.debian.in
--- a/initsystems/sysvinit/init.debian.in
+++ b/initsystems/sysvinit/init.debian.in
@@ -1,3 +1,6 @@
+
+FIXME
+
 #!/bin/sh
 # IPsec startup and shutdown script
 #
@@ -19,6 +22,7 @@
 # Copyright (C) 2002              Michael Richardson <mcr@freeswan.org>
 # Copyright (C) 2006              Michael Richardson <mcr@xelerance.com>
 # Copyright (C) 2008              Michael Richardson <mcr@sandelman.ca>
+# Copyright (C) 2008-2011         Tuomo Soini <tis@foobar.fi>
 # Copyright (C) 2012              Paul Wouters <paul@libreswan.org>
 # 
 # This program is free software; you can redistribute it and/or modify it
@@ -46,13 +50,17 @@
 #
 # chkconfig: - 47 76
 # description: IPsec provides encrypted and authenticated communications; \
-# KLIPS is the kernel half of it, Pluto is the user-level management daemon.
+# NETKEY/KLIPS is the kernel half of it, Pluto is the user-level management daemon.
 
-# where the private directory and the config files are
-IPSEC_EXECDIR="${IPSEC_EXECDIR-@IPSEC_EXECDIR@}"
-IPSEC_LIBDIR="${IPSEC_LIBDIR-@IPSEC_LIBDIR@}"
-IPSEC_SBINDIR="${IPSEC_SBINDIR-@IPSEC_SBINDIR@}"
-IPSEC_CONFS="${IPSEC_CONFS-@IPSEC_CONFS@}"
+# Source function library.
+. /etc/init.d/functions
+
+# Check that networking is up.
+[ "${NETWORKING}" = "no" ] && exit 6
+
+if [ ! -f /etc/sysconfig/network ]; then
+    exit 6
+fi
 
 if [ `id -u` -ne 0 ]
 then
@@ -61,15 +69,12 @@ then
     exit 4
 fi
 
-if test " $IPSEC_DIR" = " "	# if we were not called by the ipsec command
-then
-    # we must establish a suitable PATH ourselves
-    PATH="${IPSEC_SBINDIR}":/sbin:/usr/sbin:/usr/local/bin:/bin:/usr/bin
-    export PATH
+# where the private directory and the config files are
+IPSEC_EXECDIR="${IPSEC_EXECDIR-@IPSEC_EXECDIR@}"
+IPSEC_LIBDIR="${IPSEC_LIBDIR-@IPSEC_LIBDIR@}"
+IPSEC_SBINDIR="${IPSEC_SBINDIR-@IPSEC_SBINDIR@}"
+IPSEC_CONFS="${IPSEC_CONFS-@IPSEC_CONFS@}"
 
-    IPSEC_DIR="$IPSEC_LIBDIR"
-    export IPSEC_DIR IPSEC_CONFS IPSEC_LIBDIR IPSEC_EXECDIR
-fi
 
 # Does not make any sense at all to continue without the main binary
 # But before we can quit we should check if we are on a Debian based
@@ -89,6 +94,12 @@ umask 022
 mkdir -p /var/run/pluto
 chmod 700 /var/run/pluto
 
+if test `ip addr list|grep -c cipsec` -ne 0
+then
+	echo "Cisco IPSec client is already loaded, aborting! (cipsec# device found)"
+	exit 1
+fi
+
 # which kernel are we using?
 IPSECprotostack=`ipsec addconn --liststack`
 
@@ -107,29 +118,49 @@ verify_config() {
 }
 
 start() {
-    verify_config
-    ipsec _realsetup start
+	# starting a stack will unload any loaded stack first (same or different stack)
+	case $IPSECprotostack in
+	netkey) 
+		ipsec _startnetkey start
+		;;
+	none|nostack)
+		ipsec _startklips stop
+		ipsec _startnetkey stop
+		;;
+	mast|klips) 
+	   	ipsec _startklips start
+		;;
+	*)
+		echo "unexpected stack $IPSECprotostack"
+		exit
+		;;
+	esac
+	echo -n "Starting pluto IKE daemon for IPsec: "
+
+	ipsec _plutorun &
+	RETVAL=$?
+	return $RETVAL
 }
 
 
 stop() {
-    verify_config
-    ipsec _realsetup stop
+    
 }
 
 restart() {
+    verify_config
     stop
     start
 }
 
 condrestart() {
     verify_config
-    ipsec _realsetup status || exit 0
+    /etc/init.d/ipsec status || exit 0
     restart
 }
 
 status() {
-    ipsec _realsetup status
+    
     RETVAL=$?	
     return $RETVAL
 }
@@ -143,13 +174,13 @@ version() {
 
 # do it
 case "$1" in
-    start|--start)
+    start)
          start
          ;;
-    stop|--stop)
+    stop)
          stop
          ;;
-    restart|--restart)
+    restart)
          restart
  	 ;;
     reload|force-reload)
@@ -158,14 +189,14 @@ case "$1" in
     condrestart|try-restart)
          condrestart
          ;;
-    status|--status)
+    status)
          status
          ;;
     version)
          version
          ;;
     *)
-         echo "Usage: ipsec setup {start|stop|restart|reload|force-reload|condrestart|try-restart|status|version}"
+         echo "Usage: $0 {start|stop|restart|reload|force-reload|condrestart|try-restart|status|version}"
          RETVAL=2
 esac
  	
