_stackmanager: Fail if we couldn't load XFRM stack

diff --git a/programs/_stackmanager/_stackmanager.in b/programs/_stackmanager/_stackmanager.in
--- a/programs/_stackmanager/_stackmanager.in
+++ b/programs/_stackmanager/_stackmanager.in
@@ -142,6 +142,12 @@ startnetkey() {
     # Also Time before reserved kernel SPI times out
     [ -w /proc/sys/net/core/xfrm_acq_expires ] && \
 	echo ${xfrmlifetime} >/proc/sys/net/core/xfrm_acq_expires || : not writeable
+
+    # Fail on error in loading NETKEY/XFRM stack
+    if [ ! -f ${kamepfkey} ]; then
+	echo "FAILURE in loading NETKEY/XFRM stack" >&2
+	exit 1
+    fi
 }
 
 stopklips() {
