_stackmanager: Use consistent XFRM naming and update documentation

diff --git a/programs/_stackmanager/_stackmanager.in b/programs/_stackmanager/_stackmanager.in
--- a/programs/_stackmanager/_stackmanager.in
+++ b/programs/_stackmanager/_stackmanager.in
@@ -48,7 +48,7 @@ stopnetkey() {
 	ip xfrm state flush
 	ip xfrm policy flush
 	if [ -n "$(ip xfrm state)" -o -n "$(ip xfrm policy)" ]; then
-	    echo "XFRM/IPsec stack could not be cleared" >&2
+	    echo "XFRM IPsec stack could not be cleared" >&2
 	fi
 
 	if [ -f /proc/modules ]; then
@@ -150,9 +150,9 @@ startnetkey() {
 	echo "WARNING: can not change /proc/sys/net/core/xfrm_acq_expires from ${xcur} to ${xfrmlifetime}" >&2
     fi
 
-    # Fail on error in loading XFRM/IPsec stack
+    # Fail on error in loading XFRM IPsec stack
     if [ ! -f ${xfrm_stat} ]; then
-	echo "FAILURE in loading XFRM/IPsec stack" >&2
+	echo "FAILURE in loading XFRM IPsec stack" >&2
 	exit 1
     fi
 }
@@ -209,7 +209,7 @@ stop() {
 
 cryptomodules() {
     # load any OCF and CryptoAPI modules we might need for acceleration
-    # (OCF works for XFRM/IPsec and KLIPS)
+    # (OCF works for XFRM IPsec and KLIPS)
     # OCF cryptosoft is for kernel acceleration (ESP/AH)
     ${MODPROBE} cryptosoft 2>/dev/null
     # We skip cryptodev.ko because we no longer support /dev/crypto offloading
@@ -260,7 +260,7 @@ startmast() {
 startklips() {
     cryptomodules
     if [ -f ${xfrm_stat} ]; then
-	echo "Warning: found XFRM/IPsec stack loaded - attempting to unload..." >&2
+	echo "Warning: found XFRM IPsec stack loaded - attempting to unload..." >&2
 	stopnetkey --wait
 	if [ -f ${xfrm_stat} ]; then
 	    echo "FAILURE to unload KLIPS module" >&2
@@ -428,7 +428,7 @@ if [ $(id -u) -ne 0 ]; then
     exit 4
 fi
 
-if [ "$2" = "--netkey" ]; then
+if [ "$2" = "--netkey" -o "$2" = "--xfrm" ]; then
 	# manual override for use in docker
 	stack=netkey
 else
@@ -450,7 +450,7 @@ esac
 
 case ${action} in
     stop)
-	# We don't unload XFRM/IPsec on stop - only when we detect a stack
+	# We don't unload XFRM IPsec on stop - only when we detect a stack
 	# change.
 	if [ -f ${klipsstack} ]; then
 		ipsec eroute --clear
