pervasive: "cannot" is clearer and more idiomatic thant "can not"

diff --git a/programs/_stackmanager/_stackmanager.in b/programs/_stackmanager/_stackmanager.in
--- a/programs/_stackmanager/_stackmanager.in
+++ b/programs/_stackmanager/_stackmanager.in
@@ -141,7 +141,7 @@ startnetkey() {
 	    echo ${xfrmlifetime} >/proc/sys/net/core/xfrm_acq_expires
 	fi
     else
-	echo "WARNING: can not change /proc/sys/net/core/xfrm_acq_expires from ${xcur} to ${xfrmlifetime}" >&2
+	echo "WARNING: cannot change /proc/sys/net/core/xfrm_acq_expires from ${xcur} to ${xfrmlifetime}" >&2
     fi
 
     # Fail on error in loading XFRM IPsec stack
