ipsec: create NSS DB on startup when missing
- Added "ipsec --checknss" that creates-when-missing
- systemd service file runs this
- for sysvinit and the like, this is run in the _plutorun loop
- Minor cleanup of ipsec --help

diff --git a/programs/ipsec/ipsec.in b/programs/ipsec/ipsec.in
--- a/programs/ipsec/ipsec.in
+++ b/programs/ipsec/ipsec.in
@@ -30,7 +30,7 @@ PATH="${IPSEC_SBINDIR}":/sbin:/usr/sbin:/usr/local/bin:/bin:/usr/bin
 export PATH
 
 # things not to be listed in --help command list
-DONTMENTION='^(ipsec|_.*|.*\.old|.*~)$'
+DONTMENTION='^(ipsec|_.*|.*\.old|.*\.orig|.*~)$'
 
 # version numbering (details filled in by build)
 # Possibly should call a C program to invoke the version_code() function
@@ -94,8 +94,7 @@ case "${1}" in
 	echo "where <command> is one of:"
 	echo ""
 	GOTTWO=""
-	for f in $(ls "${IPSEC_EXECDIR}" | egrep -v -i "${DONTMENTION}"); do
-	    if [ -x "${IPSEC_EXECDIR}/${f}" ]; then
+	for f in start stop restart status import initnss checknss $(ls "${IPSEC_EXECDIR}" | egrep -v -i "${DONTMENTION}"); do
 		if [ -z "${GOTTWO}" ]; then
 		    # first of two entries
 		    GOTTWO="${f}"
@@ -112,16 +111,13 @@ case "${1}" in
 		    echo "${f}"
 		    GOTTWO=""
 		fi
-	    fi
 	done
 	if [ -n "${GOTTWO}" ]; then
 	    # leftover entry
 	    echo "	${GOTTWO}"
 	fi
 	echo
-	echo "See also: ipsec <command> --help"
-	echo "Most commands have their own manual pages, e.g. ipsec_auto(8)."
-	echo "ipsec stop|start|restart is an alias for ipsec setup stop|start|restart"
+	echo "See also: man ipsec <command> or ipsec <command> --help"
 	echo "See <https://libreswan.org/> for more general info."
 	fixversion
 	echo "Linux Libreswan ${version}"
@@ -138,6 +134,10 @@ case "${1}" in
 	exit 0
 	;;
     import|--import)
+	if [ $(id -u) -ne 0 ]; then
+	    echo "permision denied on nss operation (must be superuser)"
+	    exit 4
+	fi
 	if [ -z "${2}" ]; then
 	    echo "usage: ipsec import /path/to/pkcs.12" >&2
 	    exit 1
@@ -154,7 +154,11 @@ case "${1}" in
 	fi
 	exit 0
 	;;
-    initnss|--initnss)
+    initnss|--initnss|checknss|--checknss)
+	if [ $(id -u) -ne 0 ]; then
+	    echo "permision denied on nss operation (must be superuser)"
+	    exit 4
+	fi
 	if [ -n "${2}" ]; then
 	    # A lot of nss commands use -d or --configdir to specify NSS db location
 	    if [ "${2}" = "-d" -o "${2}" = "--configdir" ]; then
@@ -169,17 +173,22 @@ case "${1}" in
 	if [ -f "${IPSEC_CONFDDIR}/cert8.db" -o \
 	    -f "${IPSEC_CONFDDIR}/key3.db" -o \
 	    -f "${IPSEC_CONFDDIR}/secmod.db" ]; then
+	    # if just checking, silently quit
+	    [ "${1}" = "checknss" -o "${1}" = "--checknss" ] && exit 0
 	    echo "NSS database already initialised - aborted"
 	    echo "To wipe the old NSS database, issue: rm \"${IPSEC_CONFDDIR}/\"*.db"
 	    exit 42
 	fi
 
 	echo "Initializing NSS database"
-	echo "If you want to ensure the IPsec subsystem can start unattended,"
-	echo "   use an empty password"
+	echo "See 'man pluto' if you want to protect the NSS database with a password"
 	echo ""
 
-	certutil -N -d "${IPSEC_CONFDDIR}"
+	TEMPFILE=$(/bin/mktemp "${IPSEC_CONFDDIR}/nsspw.XXXXXXX")
+	[ $? -gt 0 ] && TEMPFILE="${IPSEC_CONFDDIR}/nsspw.$$"
+	echo > ${TEMPFILE}
+	certutil -N -f "${TEMPFILE}" -d "${IPSEC_CONFDDIR}"
+	rm -f ${TEMPFILE}
 	if [ -x /usr/sbin/restorecon ]; then
 	    restorecon -Rv "${IPSEC_CONFDDIR}"
 	fi
