ipsec: check write permission in import for better error message

diff --git a/programs/ipsec/ipsec.in b/programs/ipsec/ipsec.in
--- a/programs/ipsec/ipsec.in
+++ b/programs/ipsec/ipsec.in
@@ -225,20 +225,25 @@ ipsec_import() {
 	shift
     done
 
-    if [ -f "${IPSEC_NSSDIR}/key4.db" -a \
-	-f "${IPSEC_NSSDIR}/cert9.db" ]
-    then
-	IPSEC_NSSDIR_SQL="sql:${IPSEC_NSSDIR}"
+    if [ -d "${IPSEC_NSSDIR}" -a -w "${IPSEC_NSSDIR}" ]; then
+	if [ -f "${IPSEC_NSSDIR}/key4.db" -a \
+	    -f "${IPSEC_NSSDIR}/cert9.db" ]
+	then
+	    IPSEC_NSSDIR_SQL="sql:${IPSEC_NSSDIR}"
+	else
+	    echo "ERROR: NSS database files are missing, import aborted." >&2
+	    echo "Initialize database with command \"ipsec checknss\"." >&2
+	    exit 1
+	fi
+
+	pk12util -i "${pkcs12bundle}" -d "${IPSEC_NSSDIR_SQL}"
+	# check and correct trust bits
+	set_db_trusts
+	exit 0
     else
-	echo "ERROR: NSS database files are missing, import aborted." >&2
-	echo "Initialize database with command \"ipsec checknss\"." >&2
+	echo "ERROR: destination directory \"${IPSEC_NSSDIR}\" is missing or permission denied" >&2
 	exit 1
     fi
-
-    pk12util -i "${pkcs12bundle}" -d "${IPSEC_NSSDIR_SQL}"
-    # check and correct trust bits
-    set_db_trusts
-    exit 0
 }
 
 ipsec_checknss() {
